 1. Perform the following operations using Python on the Facebook metrics data sets
   a. Create data subsets
   b. Merge Data
   c. Sort Data
  d. Transposing Data
   e. Shape and reshape Data

  Data Set  Facebook metrics data sets
  https://www.kaggle.com/datasets/masoodanzar/facebook-metrics?resource=download

In [1]:
import pandas as pd

In [2]:
# read_csv() - Read a comma-separated values (csv) file into DataFrame
#  Read Facebook metrics data sets

df = pd.read_csv('dataset_Facebook.csv', sep=';')

In [3]:
# Display firt n rows of data set.   DatFrame.head(n)  return n rows from begning of the data set.  if 'n' is not specified ,then returns first 5 rows

df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [4]:
# print data set information
# The info() method prints information about the DataFrame. 
# The information contains the number of columns, column labels, column data types, memory usage, range index,
#  and the number of cells in each column 


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
Page total likes                                                       500 non-null int64
Type                                                                   500 non-null object
Category                                                               500 non-null int64
Post Month                                                             500 non-null int64
Post Weekday                                                           500 non-null int64
Post Hour                                                              500 non-null int64
Paid                                                                   499 non-null float64
Lifetime Post Total Reach                                              500 non-null int64
Lifetime Post Total Impressions                                        500 non-null int64
Lifetime Engaged Users                                                 500 non-null int64
Lifetime Post Consumers                                                500 non-null int64
Lifetime Post Consumptions                                             500 non-null int64
Lifetime Post Impressions by people who have liked your Page           500 non-null int64
Lifetime Post reach by people who like your Page                       500 non-null int64
Lifetime People who have liked your Page and engaged with your post    500 non-null int64
comment                                                                500 non-null int64
like                                                                   499 non-null float64
share                                                                  496 non-null float64
Total Interactions                                                     500 non-null int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB

# a. Create data subsets

In [5]:
# 
df_subset1 = df_subset1=df[['like','share']]
print(df_subset1)

       like  share
0      79.0   17.0
1     130.0   29.0
2      66.0   14.0
3    1572.0  147.0
4     325.0   49.0
5     152.0   33.0
6     249.0   27.0
7     325.0   14.0
8     161.0   31.0
9     113.0   26.0
10    233.0   19.0
11     88.0   18.0
12     90.0   14.0
13    137.0   10.0
14    577.0   20.0
15     86.0   18.0
16     40.0   12.0
17    678.0   20.0
18     54.0   17.0
19     34.0    8.0
20     66.0   12.0
21      0.0    0.0
22     16.0    2.0
23     72.0   24.0
24     99.0   19.0
25     88.0   18.0
26    412.0   72.0
27    100.0   17.0
28    523.0   63.0
29    143.0   13.0
..      ...    ...
470   114.0   13.0
471   160.0   57.0
472    46.0   15.0
473   136.0   42.0
474    73.0   13.0
475    65.0   19.0
476   579.0   47.0
477   101.0    5.0
478    74.0   31.0
479    84.0   36.0
480   360.0   99.0
481     5.0    2.0
482   187.0   36.0
483    69.0   26.0
484    82.0   24.0
485    12.0    2.0
486    56.0   25.0
487    44.0   21.0
488   277.0   80.0
489    74.0   28.0
490    79.0   30.0
491   105.0   46.0
492   128.0    9.0
493   185.0   55.0
494   125.0   41.0
495    53.0   26.0
496    53.0   22.0
497    93.0   18.0
498    91.0   38.0
499    91.0   28.0

[500 rows x 2 columns]

In [6]:
df[['Type','like']]

       Type    like
0     Photo    79.0
1    Status   130.0
2     Photo    66.0
3     Photo  1572.0
4     Photo   325.0
5    Status   152.0
6     Photo   249.0
7     Photo   325.0
8    Status   161.0
9     Photo   113.0
10   Status   233.0
11    Photo    88.0
12    Photo    90.0
13    Photo   137.0
14    Photo   577.0
15   Status    86.0
16    Photo    40.0
17    Photo   678.0
18   Status    54.0
19    Photo    34.0
20    Photo    66.0
21    Photo     0.0
22     Link    16.0
23    Photo    72.0
24   Status    99.0
25   Status    88.0
26   Status   412.0
27    Photo   100.0
28    Photo   523.0
29    Video   143.0
..      ...     ...
470    Link   114.0
471   Photo   160.0
472   Photo    46.0
473   Photo   136.0
474   Photo    73.0
475   Photo    65.0
476   Photo   579.0
477    Link   101.0
478   Photo    74.0
479   Photo    84.0
480   Photo   360.0
481    Link     5.0
482   Photo   187.0
483   Photo    69.0
484   Photo    82.0
485    Link    12.0
486   Photo    56.0
487   Photo    44.0
488   Photo   277.0
489   Photo    74.0
490   Photo    79.0
491   Photo   105.0
492    Link   128.0
493   Photo   185.0
494   Photo   125.0
495   Photo    53.0
496   Photo    53.0
497   Photo    93.0
498   Photo    91.0
499   Photo    91.0

[500 rows x 2 columns]

In [7]:
df_subset2=df[df['like']>100]
print(df_subset2)

     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
1              139441  Status         2          12             3         10
3              139441   Photo         2          12             2         10
4              139441   Photo         2          12             2          3
5              139441  Status         2          12             1          9
6              139441   Photo         3          12             1          3
7              139441   Photo         3          12             7          9
8              139441  Status         2          12             7          3
9              139441   Photo         3          12             6         10
10             139441  Status         2          12             5         10
13             139441   Photo         2          12             5          3
14             138414   Photo         2          12             4          5
17             138414   Photo         1          12             2         12
26             138458  Status         2          12             5         11
28             138895   Photo         2          12             5          3
29             138895   Video         1          12             4         11
30             138895   Photo         2          12             4          2
32             138895   Photo         3          12             3          3
35             138895   Photo         2          12             1         11
38             138895  Status         2          12             7          9
40             138895  Status         2          12             6         11
41             138895    Link         1          12             6          3
46             138353  Status         1          12             3         11
51             138329   Photo         1          11             1          3
52             138329   Photo         1          11             7          9
56             138329   Photo         1          11             5         11
59             138329   Photo         1          11             4          3
60             138185   Photo         1          11             3         11
61             138185   Photo         1          11             3          2
62             138185   Photo         1          11             2         10
63             138185   Photo         1          11             2          3
..                ...     ...       ...         ...           ...        ...
437            100732   Photo         1           3             6         10
442             98195   Photo         3           3             4         13
446             96749   Photo         1           3             1          2
449             93684   Photo         1           2             6         13
450             93577   Photo         1           2             6          6
454             93149   Photo         3           2             4          3
455             93042   Photo         3           2             3         13
457             92828   Photo         1           2             3          6
458             92721   Photo         3           2             2         13
459             92614   Photo         2           2             2          3
460             92507   Photo         3           2             1         13
462             92293   Photo         3           2             7         13
463             92186   Photo         3           2             7          2
464             92079   Photo         1           2             6         13
465             91972   Photo         3           2             6          3
467             91758   Photo         2           2             5          3
468             91651   Photo         1           2             4         12
469             91544   Photo         3           2             4          3
470             91437    Link         1           2             3         13
471             91330   Photo         3           2             3          3
473             91116   Photo         3           2             2          4
476             86909   Photo         1           1             6         10
477             86909    Link         1           1             6          4
480             86909   Photo         2           1             4         11
482             86491   Photo         3           1             3         10
488             85979   Photo         3           1             7         10
491             85979   Photo         3           1             6          3
492             85979    Link         1           1             5         11
493             85093   Photo         3           1             1          2
494             85093   Photo         3           1             7         10

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
1     0.0                      10460                            19057
3     1.0                      50128                            87991
4     0.0                       7244                            13594
5     0.0                      10472                            20849
6     1.0                      11692                            19479
7     1.0                      13720                            24137
8     0.0                      11844                            22538
9     0.0                       4694                             8668
10    0.0                      21744                            42334
13    0.0                       2549                             4896
14    1.0                      22784                            39941
17    1.0                      53264                           111785
26    0.0                      19552                            34143
28    0.0                       9560                            18264
29    1.0                      36208                            61262
30    0.0                       4940                             9390
32    0.0                       5280                             9578
35    0.0                       4512                             7808
38    0.0                      17576                            33058
40    0.0                      13280                            24198
41    1.0                      18480                            28438
46    0.0                      16576                            30612
51    1.0                      25248                            40125
52    0.0                       4894                             8899
56    0.0                       5812                            10465
59    1.0                      27072                            84885
60    1.0                      10940                            27951
61    1.0                      50912                           164528
62    1.0                      28752                            47358
63    1.0                      27216                            81908
..    ...                        ...                              ...
437   0.0                     122944                           457509
442   0.0                      34480                           191207
446   1.0                      98816                           125026
449   1.0                      27056                           162816
450   0.0                      20528                            33000
454   0.0                       9528                            16535
455   0.0                       8500                            14157
457   0.0                      28128                            42940
458   0.0                       7228                            12627
459   1.0                       5290                             9100
460   0.0                      55520                           665792
462   1.0                      10040                            17029
463   1.0                     153536                           497910
464   0.0                     158208                           453213
465   0.0                       6484                            10832
467   1.0                      15880                            51571
468   0.0                      15288                            31467
469   0.0                       9528                            16779
470   0.0                       9356                            14986
471   0.0                       7732                            13264
473   1.0                       7132                            12060
476   1.0                      37088                            10966
477   0.0                      39600                             7927
480   0.0                      11484                            20696
482   0.0                      66784                             9456
488   0.0                       9700                            17442
491   1.0                       6184                            10228
492   0.0                      45920                             5808
493   0.0                       8412                            13960
494   0.0                       5400                             9218

     Lifetime Engaged Users  Lifetime Post Consumers  \
1                      1457                     1361
3                      2211                      790
4                       671                      410
5                      1191                     1073
6                       481                      265
7                       537                      232
8                      1530                     1407
9                       280                      183
10                     4258                     4100
13                      249                      134
14                      887                      337
17                     1706                     1103
26                     2806                     2531
28                      973                      559
29                     1141                     1068
30                      385                      306
32                      368                      237
35                      423                      284
38                     5352                     5202
40                     2055                     1912
41                      517                      366
46                     3572                     3464
51                      726                      467
52                      355                      181
56                      343                      204
59                      421                      304
60                      417                      335
61                      630                      513
62                      802                      654
63                      541                      335
..                      ...                      ...
437                    1373                     1268
442                    1591                     1156
446                   11452                    11328
449                    2299                     2127
450                    1876                     1800
454                    1383                     1288
455                    1095                     1029
457                    2283                     2190
458                    1239                     1189
459                    1053                      994
460                    4544                     3586
462                    1429                     1346
463                    1713                     1633
464                    2482                     2319
465                    1166                     1115
467                    1188                     1071
468                    1573                     1401
469                    1245                     1175
470                     448                      381
471                    1066                     1002
473                    1004                      944
476                    2728                     2288
477                     572                      496
480                    1762                     1635
482                    2969                     2833
488                    1407                     1271
491                     956                      901
492                     753                      655
493                    1179                     1111
494                     810                      756

     Lifetime Post Consumptions  \
1                          1674
3                          1119
4                           580
5                          1389
6                           364
7                           305
8                          1692
9                           250
10                         4540
13                          168
14                          417
17                         1655
26                         3420
28                          885
29                         1728
30                          501
32                          345
35                          431
38                         6547
40                         2720
41                          460
46                         4802
51                          863
52                          264
56                          301
59                          487
60                          591
61                          952
62                         1268
63                          540
..                          ...
437                        2106
442                        1926
446                       18115
449                        2737
450                        2654
454                        1834
455                        1422
457                        3400
458                        1612
459                        1326
460                        6624
462                        2022
463                        2493
464                        3412
465                        1441
467                        1410
468                        2110
469                        1725
470                         505
471                        1336
473                        1226
476                        3183
477                         581
480                        2741
482                        3645
488                        2007
491                        1140
492                         763
493                        1632
494                        1003

     Lifetime Post Impressions by people who have liked your Page  \
1                                                11710
3                                                61027
4                                                 6228
5                                                16034
6                                                15432
7                                                19728
8                                                15220
9                                                 4309
10                                               37849
13                                                3631
14                                               34415
17                                               92512
26                                               17748
28                                                9217
29                                               30131
30                                                5860
32                                                4480
35                                                5183
38                                               23135
40                                               17627
41                                               12078
46                                               24363
51                                               16132
52                                                4914
56                                                4976
59                                               35637
60                                               15066
61                                               54653
62                                               14091
63                                               26869
..                                                 ...
437                                              72846
442                                             184270
446                                              16682
449                                             160270
450                                              14636
454                                              11276
455                                               9670
457                                               9183
458                                               9781
459                                               6285
460                                             648611
462                                              11744
463                                               8907
464                                              81938
465                                               7316
467                                              47976
468                                              28247
469                                              11885
470                                              13919
471                                               8753
473                                               8294
476                                              66311
477                                              12522
480                                               8774
482                                              17809
488                                               8872
491                                               6085
492                                              15766
493                                               8632
494                                               5654

     Lifetime Post reach by people who like your Page  \
1                                                6112
3                                               32048
4                                                3200
5                                                7852
6                                                9328
7                                               11056
8                                                7912
9                                                2324
10                                              18952
13                                               1917
14                                              19312
17                                              39776
26                                               9824
28                                               4748
29                                              14112
30                                               2930
32                                               2422
35                                               2954
38                                              11792
40                                               9344
41                                               6752
46                                              12888
51                                               8608
52                                               2712
56                                               2764
59                                               9712
60                                               5100
61                                              12704
62                                               7456
63                                               7760
..                                                ...
437                                             13184
442                                             30720
446                                             10336
449                                             25424
450                                              7632
454                                              6260
455                                              5640
457                                              4560

In [8]:
df.loc[[1,3,7]]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339

In [9]:
# df.iloc[row_start: row_end  , column_start : column_end]

df.iloc[1:3,0:2]

   Page total likes    Type
1            139441  Status
2            139441   Photo

In [10]:
df.loc[5:8]

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192

In [11]:
df.loc[1:7,['like','share']]

     like  share
1   130.0   29.0
2    66.0   14.0
3  1572.0  147.0
4   325.0   49.0
5   152.0   33.0
6   249.0   27.0
7   325.0   14.0

# b. Merge Data

In [12]:
# Create two subsets of a data sets  and merge data from these two subsets.

In [13]:
# Display data set information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
Page total likes                                                       500 non-null int64
Type                                                                   500 non-null object
Category                                                               500 non-null int64
Post Month                                                             500 non-null int64
Post Weekday                                                           500 non-null int64
Post Hour                                                              500 non-null int64
Paid                                                                   499 non-null float64
Lifetime Post Total Reach                                              500 non-null int64
Lifetime Post Total Impressions                                        500 non-null int64
Lifetime Engaged Users                                                 500 non-null int64
Lifetime Post Consumers                                                500 non-null int64
Lifetime Post Consumptions                                             500 non-null int64
Lifetime Post Impressions by people who have liked your Page           500 non-null int64
Lifetime Post reach by people who like your Page                       500 non-null int64
Lifetime People who have liked your Page and engaged with your post    500 non-null int64
comment                                                                500 non-null int64
like                                                                   499 non-null float64
share                                                                  496 non-null float64
Total Interactions                                                     500 non-null int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB

In [14]:
# create  subset1 with data from row 1 to row 5 and columns  'Category','like','share','Type' of Facebook metric data set


subset1 = df.loc[1:5,['Category','like','share','Type']]
subset1

   Category    like  share    Type
1         2   130.0   29.0  Status
2         3    66.0   14.0   Photo
3         2  1572.0  147.0   Photo
4         2   325.0   49.0   Photo
5         2   152.0   33.0  Status

In [15]:
# create  subset2 with data from row 11 to row 13 and in columns  'Category','like','share','Type' of Facebook metric data set

subset2 = df.loc[11:13,['Category','like','share','Type']]
subset2

    Category   like  share   Type
11         2   88.0   18.0  Photo
12         2   90.0   14.0  Photo
13         2  137.0   10.0  Photo

In [16]:
print(subset1, '\n\n', subset2)

   Category    like  share    Type
1         2   130.0   29.0  Status
2         3    66.0   14.0   Photo
3         2  1572.0  147.0   Photo
4         2   325.0   49.0   Photo
5         2   152.0   33.0  Status

     Category   like  share   Type
11         2   88.0   18.0  Photo
12         2   90.0   14.0  Photo
13         2  137.0   10.0  Photo

In [17]:
# merge subset1 and subset 2  along axis 0 
# ( Axis 0 means row wise,axis 1 means column wise ) (  i.e Append rows of subset2 after rows of subset1)

merge_set = pd.concat([subset1, subset2], axis=0)
print(merge_set)

    Category    like  share    Type
1          2   130.0   29.0  Status
2          3    66.0   14.0   Photo
3          2  1572.0  147.0   Photo
4          2   325.0   49.0   Photo
5          2   152.0   33.0  Status
11         2    88.0   18.0   Photo
12         2    90.0   14.0   Photo
13         2   137.0   10.0   Photo

In [18]:
# Display the size of merge set.  i.e after combining two sets

merge_set.shape

(8, 4)

# Sorting Data

In [19]:
# Sort data in ascending order of 'like'

df.sort_values(by='like',ascending=True)

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
441,98195,Photo,1,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0
122,136393,Photo,1,10,7,8,0.0,619,1096,257,254,292,951,516,217,1,1.0,2.0,4
422,102112,Photo,1,3,1,19,0.0,238,570,143,142,834,567,236,99,0,2.0,0.0,2
428,100732,Photo,1,3,7,15,0.0,5132,9067,398,398,1690,9065,5132,393,0,2.0,0.0,2
120,136393,Photo,1,10,7,9,0.0,584,1029,273,271,308,943,511,232,0,2.0,NaN,2
429,100732,Photo,1,3,7,15,0.0,3772,6971,144,144,1033,6932,3758,140,0,3.0,0.0,3
123,136393,Photo,1,10,7,7,0.0,617,1071,229,223,265,935,521,191,1,3.0,2.0,6
129,136393,Photo,1,10,6,12,0.0,754,1510,206,205,252,1430,690,175,0,3.0,0.0,3
128,136393,Photo,1,10,6,13,0.0,645,1117,195,192,224,989,554,166,0,4.0,1.0,5
432,100732,Photo,1,3,6,17,0.0,452,726,186,184,889,721,450,114,0,4.0,1.0,5
431,100732,Photo,1,3,7,12,0.0,4094,7469,206,203,1420,7451,4088,200,0,4.0,0.0,4
115,136642,Photo,1,10,7,12,1.0,813,1568,323,319,387,1402,695,280,0,4.0,2.0,6
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
430,100732,Link,1,3,7,14,0.0,2933,5144,24,23,26,3972,2012,19,0,6.0,0.0,6
426,100732,Photo,1,3,7,18,0.0,391,746,131,130,766,723,380,93,0,6.0,1.0,7
119,136393,Photo,1,10,7,10,0.0,786,1573,263,257,318,1401,660,222,0,6.0,2.0,8
118,136642,Photo,1,10,7,10,0.0,834,1570,399,392,510,1390,704,351,0,7.0,2.0,9
117,136642,Photo,1,10,7,11,0.0,729,1374,303,298,331,1284,650,262,0,7.0,0.0,7
124,136393,Photo,1,10,7,6,0.0,677,1285,251,246,297,1210,615,211,0,7.0,NaN,7
125,136393,Photo,1,10,7,5,0.0,677,1240,236,228,264,1098,580,196,0,7.0,2.0,9
131,136393,Photo,1,10,6,9,0.0,3906,8239,868,863,2632,7736,3768,774,0,7.0,3.0,10
132,136393,Photo,1,10,6,9,0.0,659,1158,199,194,239,1041,576,169,1,7.0,2.0,10
130,136393,Photo,1,10,6,11,0.0,910,1673,207,201,247,1503,782,176,0,8.0,2.0,10
127,136393,Photo,1,10,6,13,0.0,747,1443,226,220,287,1252,632,194,0,9.0,1.0,10
213,132201,Photo,3,8,4,11,1.0,1006,1594,277,268,354,1055,651,187,1,11.0,3.0,15
133,136393,Photo,1,10,6,8,0.0,652,1331,214,206,249,1249,588,182,0,11.0,1.0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,135428,Photo,3,9,4,2,1.0,10748,19724,892,498,719,13674,7624,704,8,485.0,64.0,557
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
264,128032,Photo,3,7,7,3,0.0,38576,55398,1355,890,1328,17365,12624,827,7,529.0,60.0,596
272,127082,Photo,1,7,3,3,1.0,76096,94644,2889,2495,4596,31096,19744,1276,22,534.0,31.0,587
240,130791,Photo,3,7,5,3,0.0,19968,35161,1016,592,909,26701,14792,757,6,535.0,83.0,624
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
328,120050,Photo,3,5,4,12,0.0,39040,55633,1684,1183,2123,32021,19712,1101,16,617.0,58.0,691
442,98195,Photo,3,3,4,13,0.0,34480,191207,1591,1156,1926,184270,30720,1292,10,664.0,97.0,771
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
270,128032,Photo,2,7,4,5,1.0,53056,65260,2003,1412,2089,23679,17104,975,6,696.0,28.0,730
67,138185,Photo,1,11,7,3,1.0,53456,93790,1576,995,1469,32646,14912,884,20,697.0,70.0,787
254,129600,Photo,3,7,5,3,0.0,54256,82011,1620,963,1419,42128,24224,977,10,755.0,58.0,823
191,133679,Photo,3,8,1,10,0.0,19648,33643,1359,695,990,24034,13528,1020,9,766.0,43.0,818
391,109670,Photo,2,4,1,13,1.0,32208,55696,1933,1367,2123,43980,24720,1568,6,766.0,109.0,881
346,117764,Photo,3,5,7,2,0.0,38960,65149,2298,1702,3000,57722,34368,1978,37,821.0,90.0,948
142,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
206,132201,Photo,1,8,1,3,0.0,50640,121234,2240,1577,2779,92348,34880,1790,4,859.0,68.0,931
105,137020,Photo,1,10,2,4,0.0,70144,111745,3216,2628,4782,43671,20608,1542,42,955.0,139.0,1136
176,135195,Photo,3,9,6,3,1.0,22304,37159,1805,984,1618,22864,13304,1349,29,1047.0,98.0,1174
199,132817,Photo,3,8,4,10,0.0,33536,64850,1954,1016,1678,50076,24448,1564,33,1155.0,102.0,1290
323,123047,Photo,3,6,1,10,0.0,56672,104966,2579,1334,1850,78678,37408,1831,20,1372.0,47.0,1439
101,137020,Photo,2,10,4,3,0.0,68896,104952,2624,1326,1952,35707,19840,1354,26,1505.0,95.0,1626
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
111,136736,Photo,1,10,6,8,0.0,1261,2158,37,37,49,1911,1077,33,0,NaN,NaN,0

In [20]:
#  Sort data in descending order of 'like' column in Facebbok metric data set and use 'mergesort' method for sorting

df.sort_values(by ='like',ascending=False, kind='mergsort')

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334
379,111620,Photo,3,4,1,14,1.0,105632,147918,3984,2254,3391,48575,27328,1936,51,1998.0,128.0,2177
349,117764,Photo,3,5,5,13,0.0,81856,124753,3000,1637,2718,52477,27392,1756,45,1639.0,122.0,1806
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
101,137020,Photo,2,10,4,3,0.0,68896,104952,2624,1326,1952,35707,19840,1354,26,1505.0,95.0,1626
323,123047,Photo,3,6,1,10,0.0,56672,104966,2579,1334,1850,78678,37408,1831,20,1372.0,47.0,1439
199,132817,Photo,3,8,4,10,0.0,33536,64850,1954,1016,1678,50076,24448,1564,33,1155.0,102.0,1290
176,135195,Photo,3,9,6,3,1.0,22304,37159,1805,984,1618,22864,13304,1349,29,1047.0,98.0,1174
105,137020,Photo,1,10,2,4,0.0,70144,111745,3216,2628,4782,43671,20608,1542,42,955.0,139.0,1136
142,136013,Status,2,10,3,2,1.0,31136,59964,6164,5934,9237,35977,18048,4376,60,859.0,90.0,1009
206,132201,Photo,1,8,1,3,0.0,50640,121234,2240,1577,2779,92348,34880,1790,4,859.0,68.0,931
346,117764,Photo,3,5,7,2,0.0,38960,65149,2298,1702,3000,57722,34368,1978,37,821.0,90.0,948
191,133679,Photo,3,8,1,10,0.0,19648,33643,1359,695,990,24034,13528,1020,9,766.0,43.0,818
391,109670,Photo,2,4,1,13,1.0,32208,55696,1933,1367,2123,43980,24720,1568,6,766.0,109.0,881
254,129600,Photo,3,7,5,3,0.0,54256,82011,1620,963,1419,42128,24224,977,10,755.0,58.0,823
67,138185,Photo,1,11,7,3,1.0,53456,93790,1576,995,1469,32646,14912,884,20,697.0,70.0,787
270,128032,Photo,2,7,4,5,1.0,53056,65260,2003,1412,2089,23679,17104,975,6,696.0,28.0,730
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
442,98195,Photo,3,3,4,13,0.0,34480,191207,1591,1156,1926,184270,30720,1292,10,664.0,97.0,771
328,120050,Photo,3,5,4,12,0.0,39040,55633,1684,1183,2123,32021,19712,1101,16,617.0,58.0,691
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
240,130791,Photo,3,7,5,3,0.0,19968,35161,1016,592,909,26701,14792,757,6,535.0,83.0,624
272,127082,Photo,1,7,3,3,1.0,76096,94644,2889,2495,4596,31096,19744,1276,22,534.0,31.0,587
264,128032,Photo,3,7,7,3,0.0,38576,55398,1355,890,1328,17365,12624,827,7,529.0,60.0,596
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
167,135428,Photo,3,9,4,2,1.0,10748,19724,892,498,719,13674,7624,704,8,485.0,64.0,557
242,130791,Status,2,7,4,6,0.0,17360,33613,2573,2448,6017,23338,11800,1905,9,484.0,79.0,572
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213,132201,Photo,3,8,4,11,1.0,1006,1594,277,268,354,1055,651,187,1,11.0,3.0,15
127,136393,Photo,1,10,6,13,0.0,747,1443,226,220,287,1252,632,194,0,9.0,1.0,10
130,136393,Photo,1,10,6,11,0.0,910,1673,207,201,247,1503,782,176,0,8.0,2.0,10
117,136642,Photo,1,10,7,11,0.0,729,1374,303,298,331,1284,650,262,0,7.0,0.0,7
118,136642,Photo,1,10,7,10,0.0,834,1570,399,392,510,1390,704,351,0,7.0,2.0,9
124,136393,Photo,1,10,7,6,0.0,677,1285,251,246,297,1210,615,211,0,7.0,NaN,7
125,136393,Photo,1,10,7,5,0.0,677,1240,236,228,264,1098,580,196,0,7.0,2.0,9
131,136393,Photo,1,10,6,9,0.0,3906,8239,868,863,2632,7736,3768,774,0,7.0,3.0,10
132,136393,Photo,1,10,6,9,0.0,659,1158,199,194,239,1041,576,169,1,7.0,2.0,10
119,136393,Photo,1,10,7,10,0.0,786,1573,263,257,318,1401,660,222,0,6.0,2.0,8
426,100732,Photo,1,3,7,18,0.0,391,746,131,130,766,723,380,93,0,6.0,1.0,7
430,100732,Link,1,3,7,14,0.0,2933,5144,24,23,26,3972,2012,19,0,6.0,0.0,6
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
115,136642,Photo,1,10,7,12,1.0,813,1568,323,319,387,1402,695,280,0,4.0,2.0,6
128,136393,Photo,1,10,6,13,0.0,645,1117,195,192,224,989,554,166,0,4.0,1.0,5
431,100732,Photo,1,3,7,12,0.0,4094,7469,206,203,1420,7451,4088,200,0,4.0,0.0,4
432,100732,Photo,1,3,6,17,0.0,452,726,186,184,889,721,450,114,0,4.0,1.0,5
123,136393,Photo,1,10,7,7,0.0,617,1071,229,223,265,935,521,191,1,3.0,2.0,6
129,136393,Photo,1,10,6,12,0.0,754,1510,206,205,252,1430,690,175,0,3.0,0.0,3
429,100732,Photo,1,3,7,15,0.0,3772,6971,144,144,1033,6932,3758,140,0,3.0,0.0,3
120,136393,Photo,1,10,7,9,0.0,584,1029,273,271,308,943,511,232,0,2.0,NaN,2
422,102112,Photo,1,3,1,19,0.0,238,570,143,142,834,567,236,99,0,2.0,0.0,2
428,100732,Photo,1,3,7,15,0.0,5132,9067,398,398,1690,9065,5132,393,0,2.0,0.0,2
122,136393,Photo,1,10,7,8,0.0,619,1096,257,254,292,951,516,217,1,1.0,2.0,4
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
76,137893,Photo,1,11,3,2,0.0,1228,2392,17,17,19,2392,1228,17,0,0.0,0.0,0
100,137020,Photo,1,10,4,9,1.0,1357,2453,37,37,55,2154,1120,32,0,0.0,0.0,0
417,104070,Photo,1,3,3,10,0.0,1874,2474,25,25,31,1483,1062,15,0,0.0,0.0,0
441,98195,Photo,1,3,5,4,1.0,1845,2670,9,9,9,1614,1008,9,0,0.0,0.0,0
111,136736,Photo,1,10,6,8,0.0,1261,2158,37,37,49,1911,1077,33,0,NaN,NaN,0

# d. Transposing Data

In [21]:
# Get transpose of data.  DataFrame.transpose()  converts rows into column

result= df.transpose()
print(result)

                                                       0       1       2    \
Page total likes                                    139441  139441  139441
Type                                                 Photo  Status   Photo
Category                                                 2       2       3
Post Month                                              12      12      12
Post Weekday                                             4       3       3
Post Hour                                                3      10       3
Paid                                                     0       0       0
Lifetime Post Total Reach                             2752   10460    2413
Lifetime Post Total Impressions                       5091   19057    4373
Lifetime Engaged Users                                 178    1457     177
Lifetime Post Consumers                                109    1361     113
Lifetime Post Consumptions                             159    1674     154
Lifetime Post Impressions by people who have li...    3078   11710    2812
Lifetime Post reach by people who like your Page      1640    6112    1503
Lifetime People who have liked your Page and en...     119    1108     132
comment                                                  4       5       0
like                                                    79     130      66
share                                                   17      29      14
Total Interactions                                     100     164      80

                                                       3       4       5    \
Page total likes                                    139441  139441  139441
Type                                                 Photo   Photo  Status
Category                                                 2       2       2
Post Month                                              12      12      12
Post Weekday                                             2       2       1
Post Hour                                               10       3       9
Paid                                                     1       0       0
Lifetime Post Total Reach                            50128    7244   10472
Lifetime Post Total Impressions                      87991   13594   20849
Lifetime Engaged Users                                2211     671    1191
Lifetime Post Consumers                                790     410    1073
Lifetime Post Consumptions                            1119     580    1389
Lifetime Post Impressions by people who have li...   61027    6228   16034
Lifetime Post reach by people who like your Page     32048    3200    7852
Lifetime People who have liked your Page and en...    1386     396    1016
comment                                                 58      19       1
like                                                  1572     325     152
share                                                  147      49      33
Total Interactions                                    1777     393     186

                                                       6       7       8    \
Page total likes                                    139441  139441  139441
Type                                                 Photo   Photo  Status
Category                                                 3       3       2
Post Month                                              12      12      12
Post Weekday                                             1       7       7
Post Hour                                                3       9       3
Paid                                                     1       1       0
Lifetime Post Total Reach                            11692   13720   11844
Lifetime Post Total Impressions                      19479   24137   22538
Lifetime Engaged Users                                 481     537    1530
Lifetime Post Consumers                                265     232    1407
Lifetime Post Consumptions                             364     305    1692
Lifetime Post Impressions by people who have li...   15432   19728   15220
Lifetime Post reach by people who like your Page      9328   11056    7912
Lifetime People who have liked your Page and en...     379     422    1250
comment                                                  3       0       0
like                                                   249     325     161
share                                                   27      14      31
Total Interactions                                     279     339     192

                                                       9    ...      490  \
Page total likes                                    139441  ...    85979
Type                                                 Photo  ...    Photo
Category                                                 3  ...        3
Post Month                                              12  ...        1
Post Weekday                                             6  ...        6
Post Hour                                               10  ...       11
Paid                                                     0  ...        0
Lifetime Post Total Reach                             4694  ...     5280
Lifetime Post Total Impressions                       8668  ...     8703
Lifetime Engaged Users                                 280  ...      951
Lifetime Post Consumers                                183  ...      911
Lifetime Post Consumptions                             250  ...     1237
Lifetime Post Impressions by people who have li...    4309  ...     5757
Lifetime Post reach by people who like your Page      2324  ...     3300
Lifetime People who have liked your Page and en...     199  ...      431
comment                                                  3  ...        1
like                                                   113  ...       79
share                                                   26  ...       30
Total Interactions                                     142  ...      110

                                                      491    492    493  \
Page total likes                                    85979  85979  85093
Type                                                Photo   Link  Photo
Category                                                3      1      3
Post Month                                              1      1      1
Post Weekday                                            6      5      1
Post Hour                                               3     11      2
Paid                                                    1      0      0
Lifetime Post Total Reach                            6184  45920   8412
Lifetime Post Total Impressions                     10228   5808  13960
Lifetime Engaged Users                                956    753   1179
Lifetime Post Consumers                               901    655   1111
Lifetime Post Consumptions                           1140    763   1632
Lifetime Post Impressions by people who have li...   6085  15766   8632
Lifetime Post reach by people who like your Page     3502  10720   5348
Lifetime People who have liked your Page and en...    437    220    699
comment                                                 1      0     17
like                                                  105    128    185
share                                                  46      9     55
Total Interactions                                    152    137    257

                                                      494    495    496  \
Page total likes                                    85093  85093  81370
Type                                                Photo  Photo  Photo
Category                                                3      3      2
Post Month                                              1      1      1
Post Weekday                                            7      7      5
Post Hour                                              10      2      8
Paid                                                    0      0      0
Lifetime Post Total Reach                            5400   4684   3480
Lifetime Post Total Impressions                      9218   7536   6229
Lifetime Engaged Users                                810    733    537
Lifetime Post Consumers                               756    708    508
Lifetime Post Consumptions                           1003    985    687
Lifetime Post Impressions by people who have li...   5654   4750   3961
Lifetime Post reach by people who like your Page     3230   2876   2104
Lifetime People who have liked your Page and en...    422    392    301
comment                                                10      5      0
like                                                  125     53     53
share                                                  41     26     22
Total Interactions                                    176     84     75

                                                      497    498    499
Page total likes                                    81370  81370  81370
Type                                                Photo  Photo  Photo
Category                                                1      3      2
Post Month                                              1      1      1
Post Weekday                                            5      4      4
Post Hour                                               2     11      4
Paid                                                    0      0    NaN
Lifetime Post Total Reach                            3778   4156   4188
Lifetime Post Total Impressions                      7216   7564   7292
Lifetime Engaged Users                                625    626    564
Lifetime Post Consumers                               572    574    524
Lifetime Post Consumptions                            795    832    743
Lifetime Post Impressions by people who have li...   4742   4534   3861
Lifetime Post reach by people who like your Page     2388   2452   2200
Lifetime People who have liked your Page and en...    363    370    316
comment                                                 4      7      0
like                                                   93     91     91
share                                                  18     38     28
Total Interactions                                    115    136    119

[19 rows x 500 columns]

In [22]:
df.shape

(500, 19)

In [23]:
result.shape

(19, 500)

In [24]:
# df.loc[0:4,['like','share','Category','Type']]


selective_df=pd.DataFrame(df.iloc[0:3],columns=['like','share','Category','Type'])
print(selective_df.head(5))

    like  share  Category    Type
0   79.0   17.0         2   Photo
1  130.0   29.0         2  Status
2   66.0   14.0         3   Photo

# e. Shape and reshape Data

1. melt()
2. pivote_table()

In [25]:
# create a subset with first  3 rows and 'category','post.month','post.Hour', 'paid'


sub1 = df.loc[0:3,['Category', 'Post Month','Post Hour', 'Paid']]

sub1.melt(id_vars=['Category'])

    Category    variable  value
0          2  Post Month   12.0
1          2  Post Month   12.0
2          3  Post Month   12.0
3          2  Post Month   12.0
4          2   Post Hour    3.0
5          2   Post Hour   10.0
6          3   Post Hour    3.0
7          2   Post Hour   10.0
8          2        Paid    0.0
9          2        Paid    0.0
10         3        Paid    0.0
11         2        Paid    1.0

In [26]:
# A PivotTable is an interactive way to quickly summarize large amounts of data
# pivot() is the complete opposite of melt()

pivote_table=pd.pivot_table(selective_df,index=['Category'])
print(pivote_table)

           like  share
Category
2         104.5   23.0
3          66.0   14.0

In [27]:
pivote_table.shape

(2, 2)

In [28]:
pivote_table.reset_index(inplace=True)
print(pivote_table)

   Category   like  share
0         2  104.5   23.0
1         3   66.0   14.0

In [29]:
pivote_table.melt(id_vars=['like','share'])

    like  share  variable  value
0  104.5   23.0  Category      2
1   66.0   14.0  Category      3

In [30]:
# Example :

home_expendature = { "Month":   ['Jan'      ,'Jan'    ,'Jan'      ,'feb'          ,'feb'      ,'march'   ,'march'],
                    "category": ['transport','grocery','household','entertainment','transport','grocery','household'],
                    "amount"  : [74,          235,      175,        100,            115,        240,      225]
                   }

home_expendaturedf=pd.DataFrame(home_expendature)
print(home_expendaturedf)

   Month       category  amount
0    Jan      transport      74
1    Jan        grocery     235
2    Jan      household     175
3    feb  entertainment     100
4    feb      transport     115
5  march        grocery     240
6  march      household     225

In [31]:
pd.pivot_table(home_expendaturedf,index=['category','Month'])

                     amount
category      Month
entertainment feb       100
grocery       Jan       235
              march     240
household     Jan       175
              march     225
transport     Jan        74
              feb       115