In [43]:
import pandas as pd
import numpy as np
df=pd.read_csv("AirQuality.csv",encoding='cp1252')

C:\Users\SAMRUDDHI\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
df.head(5)

,stn_code,sampling_date,state,location,agency,type,so2,no2,rspm,spm,location_monitoring_station,pm2_5,date
0,150,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",4.8,17.4,NaN,NaN,NaN,NaN,1990-02-01
1,151,February - M021990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,3.1,7.0,NaN,NaN,NaN,NaN,1990-02-01
2,152,February - M021990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",6.2,28.5,NaN,NaN,NaN,NaN,1990-02-01
3,150,March - M031990,Andhra Pradesh,Hyderabad,NaN,"Residential, Rural and other Areas",6.3,14.7,NaN,NaN,NaN,NaN,1990-03-01
4,151,March - M031990,Andhra Pradesh,Hyderabad,NaN,Industrial Area,4.7,7.5,NaN,NaN,NaN,NaN,1990-03-01

In [3]:
#a) Cleaning the dataset

In [4]:
#  Dropping columns which are not required
df = df.drop(['stn_code','agency', 'location_monitoring_station'],axis=1)

In [5]:
df.isna().sum()

sampling_date         3
state                 0
location              3
type               5393
so2               34646
no2               16233
rspm              40222
spm              237387
pm2_5            426428
date                  7
dtype: int64

In [6]:
df = df.dropna(subset=['date'])

In [7]:
df.isna().sum()

sampling_date         0
state                 0
location              0
type               5390
so2               34643
no2               16230
rspm              40219
spm              237380
pm2_5            426421
date                  0
dtype: int64

In [8]:
#Handling missing values

In [9]:
COLS = ['so2','no2', 'rspm', 'spm', 'pm2_5']

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 435735 entries, 0 to 435738
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   sampling_date  435735 non-null  object
 1   state          435735 non-null  object
 2   location       435735 non-null  object
 3   type           430345 non-null  object
 4   so2            401092 non-null  float64
 5   no2            419505 non-null  float64
 6   rspm           395516 non-null  float64
 7   spm            198355 non-null  float64
 8   pm2_5          9314 non-null    float64
 9   date           435735 non-null  object
dtypes: float64(5), object(5)
memory usage: 36.6+ MB

In [11]:
import numpy as np
from sklearn.impute import SimpleImputer

# invoking SimpleImputer to fill missing values

imputer = SimpleImputer(missing_values = np.nan, strategy='mean')

In [12]:
df[COLS] = imputer.fit_transform(df[COLS])

In [13]:
df.head()

,sampling_date,state,location,type,so2,no2,rspm,spm,pm2_5,date
0,February - M021990,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",4.8,17.4,108.833091,220.78348,40.791467,1990-02-01
1,February - M021990,Andhra Pradesh,Hyderabad,Industrial Area,3.1,7.0,108.833091,220.78348,40.791467,1990-02-01
2,February - M021990,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.2,28.5,108.833091,220.78348,40.791467,1990-02-01
3,March - M031990,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.3,14.7,108.833091,220.78348,40.791467,1990-03-01
4,March - M031990,Andhra Pradesh,Hyderabad,Industrial Area,4.7,7.5,108.833091,220.78348,40.791467,1990-03-01

In [14]:
#Data Transformation

In [15]:
df.nunique()

sampling_date    5482
state              34
location          304
type               10
so2              4198
no2              6865
rspm             6066
spm              6669
pm2_5             434
date             5067
dtype: int64

In [16]:
df.duplicated().sum()

1135

In [17]:
df.drop_duplicates()

,sampling_date,state,location,type,so2,no2,rspm,spm,pm2_5,date
0,February - M021990,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",4.8,17.4,108.833091,220.78348,40.791467,1990-02-01
1,February - M021990,Andhra Pradesh,Hyderabad,Industrial Area,3.1,7.0,108.833091,220.78348,40.791467,1990-02-01
2,February - M021990,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.2,28.5,108.833091,220.78348,40.791467,1990-02-01
3,March - M031990,Andhra Pradesh,Hyderabad,"Residential, Rural and other Areas",6.3,14.7,108.833091,220.78348,40.791467,1990-03-01
4,March - M031990,Andhra Pradesh,Hyderabad,Industrial Area,4.7,7.5,108.833091,220.78348,40.791467,1990-03-01
...,...,...,...,...,...,...,...,...,...,...
435734,15-12-15,West Bengal,ULUBERIA,RIRUO,20.0,44.0,148.000000,220.78348,40.791467,2015-12-15
435735,18-12-15,West Bengal,ULUBERIA,RIRUO,17.0,44.0,131.000000,220.78348,40.791467,2015-12-18
435736,21-12-15,West Bengal,ULUBERIA,RIRUO,18.0,45.0,140.000000,220.78348,40.791467,2015-12-21
435737,24-12-15,West Bengal,ULUBERIA,RIRUO,22.0,50.0,143.000000,220.78348,40.791467,2015-12-24
435738,29-12-15,West Bengal,ULUBERIA,RIRUO,20.0,46.0,171.000000,220.78348,40.791467,2015-12-29

In [18]:
# Simple Replacement of Categorical Data with a Number

In [19]:
df['type'].replace({  'MO':1, 'I':2, 's':3 , 'RO':4, 'K':5, 'RIRUO':6  }, inplace=True)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 435735 entries, 0 to 435738
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   sampling_date  435735 non-null  object
 1   state          435735 non-null  object
 2   location       435735 non-null  object
 3   type           430345 non-null  object
 4   so2            435735 non-null  float64
 5   no2            435735 non-null  float64
 6   rspm           435735 non-null  float64
 7   spm            435735 non-null  float64
 8   pm2_5          435735 non-null  float64
 9   date           435735 non-null  object
dtypes: float64(5), object(5)
memory usage: 36.6+ MB

In [21]:
df['type']

0         Residential, Rural and other Areas
1                            Industrial Area
2         Residential, Rural and other Areas
3         Residential, Rural and other Areas
4                            Industrial Area
                         ...
435734                                     6
435735                                     6
435736                                     6
435737                                     6
435738                                     6
Name: type, Length: 435735, dtype: object

In [22]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df['state'] =labelencoder.fit_transform(df['state'])
df.head()

,sampling_date,state,location,type,so2,no2,rspm,spm,pm2_5,date
0,February - M021990,0,Hyderabad,"Residential, Rural and other Areas",4.8,17.4,108.833091,220.78348,40.791467,1990-02-01
1,February - M021990,0,Hyderabad,Industrial Area,3.1,7.0,108.833091,220.78348,40.791467,1990-02-01
2,February - M021990,0,Hyderabad,"Residential, Rural and other Areas",6.2,28.5,108.833091,220.78348,40.791467,1990-02-01
3,March - M031990,0,Hyderabad,"Residential, Rural and other Areas",6.3,14.7,108.833091,220.78348,40.791467,1990-03-01
4,March - M031990,0,Hyderabad,Industrial Area,4.7,7.5,108.833091,220.78348,40.791467,1990-03-01

In [23]:
# One-hot encoding is used to convert categorical variables into a format that can be readily used by machine learning algorithms.

dfAndhra = df[df['state']==0]

In [24]:
dfAndhra

,sampling_date,state,location,type,so2,no2,rspm,spm,pm2_5,date
0,February - M021990,0,Hyderabad,"Residential, Rural and other Areas",4.8,17.4,108.833091,220.78348,40.791467,1990-02-01
1,February - M021990,0,Hyderabad,Industrial Area,3.1,7.0,108.833091,220.78348,40.791467,1990-02-01
2,February - M021990,0,Hyderabad,"Residential, Rural and other Areas",6.2,28.5,108.833091,220.78348,40.791467,1990-02-01
3,March - M031990,0,Hyderabad,"Residential, Rural and other Areas",6.3,14.7,108.833091,220.78348,40.791467,1990-03-01
4,March - M031990,0,Hyderabad,Industrial Area,4.7,7.5,108.833091,220.78348,40.791467,1990-03-01
...,...,...,...,...,...,...,...,...,...,...
26363,13-12-15,0,Rajahmundry,Industrial Area,7.0,13.0,71.000000,220.78348,40.791467,2015-12-13
26364,16-12-15,0,Rajahmundry,Industrial Area,7.0,18.0,77.000000,220.78348,40.791467,2015-12-16
26365,19-12-15,0,Rajahmundry,Industrial Area,8.0,23.0,64.000000,220.78348,40.791467,2015-12-19
26366,22-12-15,0,Rajahmundry,Industrial Area,7.0,19.0,61.000000,220.78348,40.791467,2015-12-22
26367,25-12-15,0,Rajahmundry,Industrial Area,6.0,17.0,71.000000,220.78348,40.791467,2015-12-25

In [25]:
dfAndhra['location'].value_counts()

Hyderabad         7764
Visakhapatnam     7108
Vijayawada        2093
Chittoor          1003
Tirupati           986
Kurnool            857
Patancheru         698
Guntur             629
Nalgonda           618
Ramagundam         554
Nellore            408
Khammam            385
Warangal           336
Ananthapur         324
Ongole             317
Kadapa             316
Srikakulam         315
Rajahmundry        311
Eluru              300
Vishakhapatnam     297
Kakinada           288
Vizianagaram       282
Sangareddy          85
Karimnagar          67
Nizamabad           27
Name: location, dtype: int64

In [26]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(sparse=False, handle_unknown='error', drop='first')

In [27]:
pd.DataFrame(onehotencoder.fit_transform(dfAndhra[['location']]))

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26363,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26364,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
dfAndhra['location'].value_counts()

Hyderabad         7764
Visakhapatnam     7108
Vijayawada        2093
Chittoor          1003
Tirupati           986
Kurnool            857
Patancheru         698
Guntur             629
Nalgonda           618
Ramagundam         554
Nellore            408
Khammam            385
Warangal           336
Ananthapur         324
Ongole             317
Kadapa             316
Srikakulam         315
Rajahmundry        311
Eluru              300
Vishakhapatnam     297
Kakinada           288
Vizianagaram       282
Sangareddy          85
Karimnagar          67
Nizamabad           27
Name: location, dtype: int64

In [29]:
#Error correction

In [30]:
df.isnull().sum()

sampling_date       0
state               0
location            0
type             5390
so2                 0
no2                 0
rspm                0
spm                 0
pm2_5               0
date                0
dtype: int64

In [31]:
df=df.fillna(df.median())
df.isnull().sum()

sampling_date       0
state               0
location            0
type             5390
so2                 0
no2                 0
rspm                0
spm                 0
pm2_5               0
date                0
dtype: int64

In [32]:
df.describe()

,state,so2,no2,rspm,spm,pm2_5
count,435735.000000,435735.000000,435735.000000,435735.000000,435735.00000,435735.000000
mean,17.966833,10.829428,25.809659,108.833091,220.78348,40.791467
std,9.471742,10.723716,18.155263,71.333594,102.14629,4.507577
min,0.000000,0.000000,0.000000,0.000000,0.00000,3.000000
25%,12.000000,5.000000,14.000000,59.000000,203.00000,40.791467
50%,18.000000,9.000000,22.300000,97.666667,220.78348,40.791467
75%,26.000000,13.000000,32.000000,135.000000,220.78348,40.791467
max,33.000000,909.000000,876.000000,6307.033333,3380.00000,504.000000

In [33]:
 #Data model building

In [52]:
df=pd.read_csv("heart.csv")

In [54]:
from sklearn.model_selection import train_test_split

In [57]:
# Splitting our Dataset

X = df.drop('target', axis=1)
y = df.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [58]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [59]:
model = LogisticRegression()

# Train model
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

C:\Users\SAMRUDDHI\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [60]:
print("Accuracy:", accuracy_score(y_test, y_pred))

# Precision
print("Precision:", precision_score(y_test, y_pred))

# Recall
print("Recall:", recall_score(y_test, y_pred))

Accuracy: 0.8021978021978022
Precision: 0.7962962962962963
Recall: 0.86